### ISSUE TITLE
Make installcheck shouldn't depend on make install.

### ISSUE THREAD

**Issue by resuna** [decibel/pltcl#1]
Make installcheck has to be run by a user who can access postgres.
Make install has to be run by root.
That's why they're separate.

**Comment by decibel** [comment]
Install only needs to be run as root if you're installing to a root location, but I can see why that could be an issue.

I guess a good alternative would be a test target that does both. That would make it easier to test things while doing development work.

I'll make the changes tonight.

**Comment by resuna** [comment]
OK, fair enough, technically true. :)

**Comment by decibel** [comment]
Fixed by 5c9ffda.
